"""initial migrations

Revision ID: 29df44a75b46
Revises: f1e194741884
Create Date: 2026-01-16 00:19:08.030434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29df44a75b46'
down_revision = 'f1e194741884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('toll_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_driver_zone_active'))
        batch_op.drop_index(batch_op.f('ix_toll_entries_driver_id'))
        batch_op.drop_index(batch_op.f('ix_toll_entries_zone_id'))

    op.drop_table('toll_entries')
    with op.batch_alter_table('tolls_paid', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_tolls_paid_checkout_request_id'))
        batch_op.drop_index(batch_op.f('ix_tolls_paid_created_at'))
        batch_op.drop_index(batch_op.f('ix_tolls_paid_zone_id'))
        batch_op.drop_constraint(batch_op.f('tolls_paid_zone_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tolls_paid', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('tolls_paid_zone_id_fkey'), 'toll_zones', ['zone_id'], ['zone_id'])
        batch_op.create_index(batch_op.f('ix_tolls_paid_zone_id'), ['zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tolls_paid_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tolls_paid_checkout_request_id'), ['checkout_request_id'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    op.create_table('toll_entries',
    sa.Column('entry_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('zone_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], name=op.f('toll_entries_driver_id_fkey')),
    sa.ForeignKeyConstraint(['payment_id'], ['tolls_paid.id'], name=op.f('toll_entries_payment_id_fkey')),
    sa.ForeignKeyConstraint(['zone_id'], ['toll_zones.zone_id'], name=op.f('toll_entries_zone_id_fkey')),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('toll_entries_pkey'))
    )
    with op.batch_alter_table('toll_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toll_entries_zone_id'), ['zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_toll_entries_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_driver_zone_active'), ['driver_id', 'zone_id', 'exit_time'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey')),
    sa.UniqueConstraint('phone_number', name=op.f('users_phone_number_key'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###
