"""add users table

Revision ID: c39844654dd2
Revises: 
Create Date: 2026-01-15 18:47:58.384858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c39844654dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('transactions')
    with op.batch_alter_table('toll_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index('idx_driver_zone_active')
        batch_op.drop_index('ix_toll_entries_driver_id')
        batch_op.drop_index('ix_toll_entries_zone_id')
        batch_op.drop_constraint('toll_entries_zone_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('toll_entries_payment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('zone_id')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('driver_id')

    with op.batch_alter_table('toll_zones', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tolls_paid', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index('ix_tolls_paid_checkout_request_id')
        batch_op.drop_index('ix_tolls_paid_created_at')
        batch_op.drop_index('ix_tolls_paid_driver_id')
        batch_op.drop_index('ix_tolls_paid_zone_id')
        batch_op.drop_constraint('tolls_paid_zone_id_fkey', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tolls_paid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tolls_paid_zone_id_fkey', 'toll_zones', ['zone_id'], ['zone_id'])
        batch_op.create_index('ix_tolls_paid_zone_id', ['zone_id'], unique=False)
        batch_op.create_index('ix_tolls_paid_driver_id', ['driver_id'], unique=False)
        batch_op.create_index('ix_tolls_paid_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_tolls_paid_checkout_request_id', ['checkout_request_id'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('toll_zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('toll_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zone_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('toll_entries_payment_id_fkey', 'tolls_paid', ['payment_id'], ['id'])
        batch_op.create_foreign_key('toll_entries_zone_id_fkey', 'toll_zones', ['zone_id'], ['zone_id'])
        batch_op.create_index('ix_toll_entries_zone_id', ['zone_id'], unique=False)
        batch_op.create_index('ix_toll_entries_driver_id', ['driver_id'], unique=False)
        batch_op.create_index('idx_driver_zone_active', ['driver_id', 'zone_id', 'exit_time'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mpesa_receipt', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
