"""create toll zones

Revision ID: f1e194741884
Revises: 
Create Date: 2026-01-12 22:09:38.458525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1e194741884'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('toll_zones',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('zone_name', sa.String(length=255), nullable=False),
    sa.Column('charge_amount', sa.Integer(), nullable=False),
    sa.Column('polygon_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('tolls_paid',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['toll_zones.zone_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tolls_paid', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tolls_paid_checkout_request_id'), ['checkout_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tolls_paid_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tolls_paid_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tolls_paid_zone_id'), ['zone_id'], unique=False)

    op.create_table('toll_entries',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['tolls_paid.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['toll_zones.zone_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    with op.batch_alter_table('toll_entries', schema=None) as batch_op:
        batch_op.create_index('idx_driver_zone_active', ['driver_id', 'zone_id', 'exit_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_toll_entries_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_toll_entries_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toll_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toll_entries_zone_id'))
        batch_op.drop_index(batch_op.f('ix_toll_entries_driver_id'))
        batch_op.drop_index('idx_driver_zone_active')

    op.drop_table('toll_entries')
    with op.batch_alter_table('tolls_paid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tolls_paid_zone_id'))
        batch_op.drop_index(batch_op.f('ix_tolls_paid_driver_id'))
        batch_op.drop_index(batch_op.f('ix_tolls_paid_created_at'))
        batch_op.drop_index(batch_op.f('ix_tolls_paid_checkout_request_id'))

    op.drop_table('tolls_paid')
    op.drop_table('toll_zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
